In [23]:
#Backpropagation application for beginners in ML
import numpy as np

In [3]:
#x = np.array([ [0,0,1], [0,1,1], [1,0,1], [1,1,1] ]) #INPUT ROWS TO THE NEURAL NETWORK
#y = np.asarray([ [0,1,1,0] ]).T #OUTPUT COLUMN

In [24]:
def nonlin(x, deriv = False):
	if(deriv==True):
		return x*(1-x) #derivative of sigmoid function
	return 1/(1+np.exp(-x)) #sigmoid function definition mathematically

In [25]:
#input dataset 
X = np.array([ [0,0,1], [0,1,1], [1,0,1], [1,1,1] ])

#output dataset
y = np.asarray([ [0,1,1,0] ]).T 

In [26]:
#deterministic 
np.random.seed(1)

In [27]:
syn0 = 2* np.random.random((3,4)) - 1 
syn1 = 2* np.random.random((4,1)) - 1 
#first layer of weights, synapse 0, connecting l0 to l1

In [28]:
#actual training
#full batch training or batch gradient descent training
for iter in range(60000):

	#forward propagation
	l0 = X 		# first layer of Network, specified by input data
	l1 = nonlin(np.dot(l0, syn0)) 	#second layer of network, known as hidden layer
	l2 = nonlin(np.dot(l1, syn1))

	#how much did we miss?
	l2_error = y - l2
    
	if((iter% 10000) == 0) :
		print("Error:" + str(np.mean(np.abs(l2_error))))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
	l2_delta = l2_error * nonlin(l2, deriv=True)
   
    # how much did each l1 value contribute to the l2 error (according to the weights)?
	l1_error = l2_delta.dot(syn1.T)
    
	# in what direction is the target l1?
	# were we really sure? if so, don't change too much.
	l1_delta = l1_error * nonlin(l1,deriv=True)

	#update weights 
	syn1 += l1.T.dot(l2_delta)
	syn0 += l0.T.dot(l1_delta)

Error:0.49641003190272537
Error:0.008584525653247159
Error:0.0057894598625078085
Error:0.004629176776769985
Error:0.003958765280273649
Error:0.0035101225678616766


In [29]:
print("Output after Training: ")
print(l1)

#Output After Training:
#[[ 0.00966449]
# [ 0.00786506]
# [ 0.99358898]
# [ 0.99211957]]

Output after Training: 
[[7.26191199e-01 1.16411907e-01 9.26183940e-01 9.97110310e-01]
 [1.66762801e-01 3.92990161e-04 1.66519465e-02 8.96576847e-01]
 [9.96229372e-01 8.95211165e-01 2.23120442e-02 8.38385421e-01]
 [9.52239003e-01 2.48589483e-02 3.07990327e-05 1.15301801e-01]]
